#!/bin/bash
#
# gpsd setup and testing
#
apt-get install gpsd-clients foxtrotgps python-gps

cat <<EOF >/etc/default/gpsd
# Default settings for gpsd.
# Please do not edit this file directly - use `dpkg-reconfigure gpsd' to
# change the options.
START_DAEMON="true"
GPSD_OPTIONS="/dev/ttyUSB0"
DEVICES=""
USBAUTO="false"
GPSD_SOCKET="/var/run/gpsd.sock"
EOF

/etc/init.d/gpsd start

wget gpslog.py

python gpslog.py
